/**
 * Bundled community beautification themes for the portable tavern.
 *
 * Each theme is a standalone SillyTavern-shaped CSS asset (no network, no JS).
 * The host activates one theme by setting
 *   document.documentElement.dataset.tavernTheme = <id>
 * so every selector below must start with html[data-tavern-theme="<id>"] and
 * only one theme is ever live. Two variable families are part of the public
 * contract: --SmartTheme* (consumed by 129+ community SillyTavern extensions)
 * and --st-* (consumed by this plugin own panel styles).
 *
 * The CSS lives in plain string arrays rather than template literals: the build
 * chain is sensitive to backticks. Keyframe names are namespaced per theme so
 * they can never collide.
 */

/** One bundled beautification theme, shaped like a SillyTavern extension. */
export interface BuiltinTheme {
  /** Directory-safe unique id, kebab-case. */
  id: string
  display_name: string
  author: string
  version: string
  /** One-line Chinese description shown in the plugin store. */
  description: string
  /** Theme tags shown as chips, e.g. ['深色','玻璃']. */
  tags: string[]
  /** The whole stylesheet. Must be scoped to html[data-tavern-theme="<id>"]. */
  css: string
}

const GLASS_CSS: string[] = [
  '/* Glassmorphism: frosted shells floating over soft light blobs. */',
  'html[data-tavern-theme="glass"]{',
  '  --SmartThemeBodyColor:#eef2fb;',
  '  --SmartThemeEmColor:#c2d4ff;',
  '  --SmartThemeQuoteColor:#a3b4dd;',
  '  --SmartThemeUnderlineColor:#8aa4e6;',
  '  --SmartThemeBlurTintColor:rgba(146,172,232,0.16);',
  '  --SmartThemeChatTintColor:rgba(118,146,214,0.12);',
  '  --SmartThemeUserMesBlurTintColor:rgba(122,168,255,0.24);',
  '  --SmartThemeBotMesBlurTintColor:rgba(196,212,248,0.10);',
  '  --SmartThemeBlurStrength:16px;',
  '  --SmartThemeShadowColor:rgba(6,10,24,0.48);',
  '  --SmartThemeBorderColor:rgba(255,255,255,0.18);',
  '  --st-accent:#79a6ff;',
  '  --st-accent-soft:rgba(121,166,255,0.24);',
  '  --st-bg:#0d1120;',
  '  --st-panel:linear-gradient(165deg,rgba(40,52,86,0.74),rgba(18,24,44,0.80));',
  '  --st-panel-2:rgba(255,255,255,0.07);',
  '  --st-text:#eef2fb;',
  '  --st-text-dim:#a8b5d4;',
  '  --st-border:rgba(255,255,255,0.16);',
  '  --st-msg-user:linear-gradient(135deg,rgba(121,166,255,0.92),rgba(154,124,255,0.86));',
  '  --st-msg-char:rgba(255,255,255,0.09);',
  '  --st-radius:16px;',
  '  --st-glow:0 12px 32px rgba(6,10,24,0.34);',
  '}',
  '',
  '/* shell: translucent slab, lit inner rim, ambient blobs behind the content */',
  'html[data-tavern-theme="glass"] .stPanel{background:var(--st-panel);color:var(--st-text);border-left:1px solid var(--st-border);border-radius:20px 0 0 20px;box-shadow:-20px 0 60px rgba(6,10,24,0.55),inset 0 1px 0 rgba(255,255,255,0.20);backdrop-filter:blur(18px) saturate(155%);-webkit-backdrop-filter:blur(18px) saturate(155%);font-family:"Segoe UI","PingFang SC","Microsoft YaHei",system-ui,sans-serif}',
  'html[data-tavern-theme="glass"] .stPanel::before{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background-image:radial-gradient(420px 320px at 88% -8%,rgba(140,180,255,0.32),transparent 62%),radial-gradient(380px 300px at 2% 102%,rgba(176,140,255,0.24),transparent 60%);animation:stGlassGlow 11s ease-in-out infinite}',
  'html[data-tavern-theme="glass"] .stPanel::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:linear-gradient(180deg,rgba(255,255,255,0.10),transparent 30%)}',
  '@keyframes stGlassGlow{0%,100%{opacity:0.68}50%{opacity:1}}',
  '',
  '/* head: a thin lit strip instead of a solid bar */',
  'html[data-tavern-theme="glass"] .stPanelHead{background:linear-gradient(180deg,rgba(255,255,255,0.14),rgba(255,255,255,0.02));border-bottom:1px solid var(--st-border);backdrop-filter:blur(10px)}',
  'html[data-tavern-theme="glass"] .stPanelTitle{font-weight:600;letter-spacing:0.02em;text-shadow:0 1px 0 rgba(255,255,255,0.16)}',
  'html[data-tavern-theme="glass"] .stClose{color:var(--st-text-dim);border-radius:10px}',
  'html[data-tavern-theme="glass"] .stClose:hover{background:rgba(255,255,255,0.16);color:#fff}',
  '',
  '/* tabs: backlit glass pills */',
  'html[data-tavern-theme="glass"] .stTabbar{background:rgba(255,255,255,0.04);border-bottom:1px solid var(--st-border);gap:6px}',
  'html[data-tavern-theme="glass"] .stTab{color:var(--st-text-dim);border-radius:12px;transition:background 0.18s ease,color 0.18s ease}',
  'html[data-tavern-theme="glass"] .stTab:hover{background:rgba(255,255,255,0.09);color:var(--st-text)}',
  'html[data-tavern-theme="glass"] .stTabActive{background:linear-gradient(180deg,rgba(255,255,255,0.24),rgba(255,255,255,0.07));color:#fff;box-shadow:inset 0 1px 0 rgba(255,255,255,0.38),0 6px 18px rgba(6,10,24,0.35)}',
  '',
  '/* chat: ambient blobs stay faintly visible through the transcript */',
  'html[data-tavern-theme="glass"] .stChatLog{background:linear-gradient(180deg,rgba(255,255,255,0.03),rgba(255,255,255,0))}',
  'html[data-tavern-theme="glass"] .stChatHead{background:rgba(255,255,255,0.03);border-bottom:1px solid var(--st-border)}',
  'html[data-tavern-theme="glass"] .stChatAvatar{border:1px solid rgba(255,255,255,0.30);box-shadow:0 6px 18px rgba(6,10,24,0.35)}',
  'html[data-tavern-theme="glass"] .stMsgBubble{border:1px solid var(--st-border);border-radius:16px;line-height:1.72;box-shadow:var(--st-glow);backdrop-filter:blur(10px)}',
  'html[data-tavern-theme="glass"] .stMsgChar .stMsgBubble{background:var(--st-msg-char);border-top-left-radius:4px;color:var(--st-text)}',
  'html[data-tavern-theme="glass"] .stMsgUser .stMsgBubble{background:var(--st-msg-user);border-color:rgba(255,255,255,0.32);border-top-right-radius:4px;color:#fff}',
  'html[data-tavern-theme="glass"] .stMsgAvatar{border:1px solid rgba(255,255,255,0.28)}',
  '',
  '/* composer and buttons: focus reads as a halo ring */',
  'html[data-tavern-theme="glass"] .stInput{background:rgba(255,255,255,0.08);border:1px solid var(--st-border);border-radius:12px;color:var(--st-text);backdrop-filter:blur(8px)}',
  'html[data-tavern-theme="glass"] .stInput::placeholder{color:rgba(200,212,240,0.50)}',
  'html[data-tavern-theme="glass"] .stInput:focus{border-color:var(--st-accent);box-shadow:0 0 0 3px var(--st-accent-soft)}',
  'html[data-tavern-theme="glass"] .stChatInput{border-top:1px solid var(--st-border)}',
  'html[data-tavern-theme="glass"] .stBtn{background:rgba(255,255,255,0.10);border:1px solid var(--st-border);border-radius:12px;color:var(--st-text);backdrop-filter:blur(8px);transition:background 0.16s ease,transform 0.16s ease}',
  'html[data-tavern-theme="glass"] .stBtn:hover{background:rgba(255,255,255,0.19);transform:translateY(-1px)}',
  'html[data-tavern-theme="glass"] .stBtnPrimary{background:linear-gradient(135deg,var(--st-accent),#a07dff);border-color:rgba(255,255,255,0.34);color:#fff;box-shadow:0 10px 24px rgba(90,130,255,0.36)}',
  'html[data-tavern-theme="glass"] .stBtnPrimary:hover{background:linear-gradient(135deg,#8db2ff,#ae8dff);filter:none}',
  'html[data-tavern-theme="glass"] .stBtnGhost{border-color:rgba(255,255,255,0.20);color:var(--st-text-dim)}',
  '',
  '/* sections and result cards: raised glass slabs */',
  'html[data-tavern-theme="glass"] .stSection{background:rgba(255,255,255,0.06);border:1px solid var(--st-border);border-radius:16px;box-shadow:0 10px 30px rgba(6,10,24,0.26);backdrop-filter:blur(10px)}',
  'html[data-tavern-theme="glass"] .stSectionHead{background:linear-gradient(180deg,rgba(255,255,255,0.13),rgba(255,255,255,0.03));color:var(--st-text)}',
  'html[data-tavern-theme="glass"] .stSectionHead:hover{background:rgba(255,255,255,0.17)}',
  'html[data-tavern-theme="glass"] .stSectionBody{background:transparent}',
  'html[data-tavern-theme="glass"] .stSectionHint,',
  'html[data-tavern-theme="glass"] .stSectionCaret,',
  'html[data-tavern-theme="glass"] .stLabel,',
  'html[data-tavern-theme="glass"] .stLiveHint,',
  'html[data-tavern-theme="glass"] .stLibMeta{color:var(--st-text-dim)}',
  'html[data-tavern-theme="glass"] .stResultWrap,',
  'html[data-tavern-theme="glass"] .stWbEntry,',
  'html[data-tavern-theme="glass"] .stLibItem{background:rgba(255,255,255,0.05);border:1px solid var(--st-border);border-radius:14px}',
  'html[data-tavern-theme="glass"] .stCardName{color:#fff;text-shadow:0 2px 12px rgba(90,130,255,0.45)}',
  'html[data-tavern-theme="glass"] .stCardTag{background:rgba(255,255,255,0.12);color:var(--st-text)}',
  '',
  '/* chips, radios, sliders and scrollbars share one frosted language */',
  'html[data-tavern-theme="glass"] .stChip{background:rgba(255,255,255,0.08);border:1px solid var(--st-border);color:var(--st-text-dim)}',
  'html[data-tavern-theme="glass"] .stChip:hover{border-color:var(--st-accent);color:var(--st-text)}',
  'html[data-tavern-theme="glass"] .stChipActive{background:var(--st-accent-soft);border-color:var(--st-accent);color:#fff}',
  'html[data-tavern-theme="glass"] .stRadio{border-color:var(--st-border);color:var(--st-text)}',
  'html[data-tavern-theme="glass"] .stRadioActive{border-color:var(--st-accent);background:var(--st-accent-soft);color:#fff}',
  'html[data-tavern-theme="glass"] .stSliderVal{background:rgba(255,255,255,0.12);border-radius:8px;color:#fff}',
  'html[data-tavern-theme="glass"] .stSwatch{box-shadow:0 4px 12px rgba(6,10,24,0.40)}',
  'html[data-tavern-theme="glass"] .stTrigger{background:rgba(24,32,54,0.74);border:1px solid var(--st-border);border-radius:12px;color:var(--st-text);backdrop-filter:blur(14px)}',
  'html[data-tavern-theme="glass"] .stRaw,',
  'html[data-tavern-theme="glass"] .stLivePre,',
  'html[data-tavern-theme="glass"] .stJsonArea{background:rgba(10,14,28,0.46);border-color:var(--st-border);border-radius:12px}',
  'html[data-tavern-theme="glass"] .stEmpty{color:var(--st-text-dim)}',
  'html[data-tavern-theme="glass"] .stSpinner{border-color:rgba(255,255,255,0.18);border-top-color:var(--st-accent)}',
  'html[data-tavern-theme="glass"] .stPanel ::-webkit-scrollbar{width:10px;height:10px}',
  'html[data-tavern-theme="glass"] .stPanel ::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.18);border-radius:999px}',
  'html[data-tavern-theme="glass"] .stSlider{accent-color:var(--st-accent)}',
  'html[data-tavern-theme="glass"] .stAvatarPreview{border:2px solid rgba(255,255,255,0.22);background:rgba(255,255,255,0.08)}',
  'html[data-tavern-theme="glass"] .stCardBlockLabel{color:var(--st-text-dim);letter-spacing:0.08em;text-transform:uppercase}',
  'html[data-tavern-theme="glass"] .stEmptyEmoji{color:rgba(255,255,255,0.35)}',
  'html[data-tavern-theme="glass"] .stPanel ::-webkit-scrollbar-track{background:transparent}',
]

const CYBER_CSS: string[] = [
  '/* Cyber neon: black chassis, cyan and magenta tube light, rolling scanlines. */',
  'html[data-tavern-theme="cyber"]{',
  '  --SmartThemeBodyColor:#d8fbff;',
  '  --SmartThemeEmColor:#00e5ff;',
  '  --SmartThemeQuoteColor:#7fe9ff;',
  '  --SmartThemeUnderlineColor:#ff2fd0;',
  '  --SmartThemeBlurTintColor:rgba(0,229,255,0.10);',
  '  --SmartThemeChatTintColor:rgba(5,7,14,0.88);',
  '  --SmartThemeUserMesBlurTintColor:rgba(255,47,208,0.14);',
  '  --SmartThemeBotMesBlurTintColor:rgba(0,229,255,0.10);',
  '  --SmartThemeBlurStrength:8px;',
  '  --SmartThemeShadowColor:rgba(0,229,255,0.28);',
  '  --SmartThemeBorderColor:rgba(0,229,255,0.42);',
  '  --st-accent:#00e5ff;',
  '  --st-accent-2:#ff2fd0;',
  '  --st-bg:#05060a;',
  '  --st-panel:rgba(6,9,18,0.97);',
  '  --st-panel-2:rgba(0,229,255,0.05);',
  '  --st-text:#d8fbff;',
  '  --st-text-dim:#5f8398;',
  '  --st-border:rgba(0,229,255,0.42);',
  '  --st-msg-user:linear-gradient(135deg,rgba(255,47,208,0.22),rgba(96,0,72,0.30));',
  '  --st-msg-char:rgba(0,229,255,0.07);',
  '  --st-radius:2px;',
  '  --st-glow:0 0 18px rgba(0,229,255,0.35);',
  '}',
  '',
  '/* shell: hard plate, cyan rim, magenta counter edge, drifting scanlines */',
  'html[data-tavern-theme="cyber"] .stPanel{background:var(--st-panel);color:var(--st-text);border-left:2px solid var(--st-accent);border-radius:0;box-shadow:-1px 0 0 rgba(255,47,208,0.35),inset 1px 0 26px rgba(0,229,255,0.10),-26px 0 62px rgba(0,229,255,0.16);font-family:"Cascadia Mono",Consolas,"SFMono-Regular",Menlo,"Microsoft YaHei",monospace;letter-spacing:0.045em}',
  'html[data-tavern-theme="cyber"] .stPanel::before{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background-image:repeating-linear-gradient(180deg,rgba(0,229,255,0.055) 0 1px,rgba(0,0,0,0) 1px 4px);animation:stCyberScan 1.8s linear infinite}',
  'html[data-tavern-theme="cyber"] .stPanel::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:radial-gradient(120% 60% at 50% 0%,rgba(0,229,255,0.13),transparent 64%),radial-gradient(90% 55% at 50% 100%,rgba(255,47,208,0.11),transparent 70%)}',
  '@keyframes stCyberScan{from{background-position:0 0}to{background-position:0 8px}}',
  '',
  '/* head: reads like a boot banner */',
  'html[data-tavern-theme="cyber"] .stPanelHead{background:linear-gradient(90deg,rgba(0,229,255,0.15),rgba(255,47,208,0.09) 68%,transparent);border-bottom:1px solid var(--st-border);box-shadow:0 1px 0 rgba(255,47,208,0.30)}',
  'html[data-tavern-theme="cyber"] .stPanelTitle{color:#eafeff;font-weight:700;letter-spacing:0.16em;text-transform:uppercase;text-shadow:0 0 10px rgba(0,229,255,0.55)}',
  'html[data-tavern-theme="cyber"] .stClose{color:var(--st-accent);border:1px solid transparent;border-radius:0}',
  'html[data-tavern-theme="cyber"] .stClose:hover{background:rgba(0,229,255,0.12);border-color:var(--st-border);color:#fff}',
  '',
  '/* tabs: uppercase labels with an underglow bar */',
  'html[data-tavern-theme="cyber"] .stTabbar{background:rgba(0,0,0,0.42);border-bottom:1px solid var(--st-border);gap:2px}',
  'html[data-tavern-theme="cyber"] .stTab{color:var(--st-text-dim);border-radius:0;font-size:11px;letter-spacing:0.14em;text-transform:uppercase;padding:8px 12px}',
  'html[data-tavern-theme="cyber"] .stTab:hover{background:rgba(0,229,255,0.07);color:var(--st-accent)}',
  'html[data-tavern-theme="cyber"] .stTabActive{background:linear-gradient(180deg,rgba(0,229,255,0.18),rgba(0,229,255,0.02));color:#eafeff;box-shadow:inset 0 -2px 0 var(--st-accent),0 0 18px rgba(0,229,255,0.35);text-shadow:0 0 8px rgba(0,229,255,0.60)}',
  '',
  '/* chat: magenta data grid under a cyan wash */',
  'html[data-tavern-theme="cyber"] .stChatLog{background-image:linear-gradient(180deg,rgba(0,229,255,0.04),transparent 42%),repeating-linear-gradient(0deg,rgba(255,47,208,0.035) 0 1px,transparent 1px 28px)}',
  'html[data-tavern-theme="cyber"] .stChatHead{background:rgba(0,229,255,0.04);border-bottom:1px solid var(--st-border)}',
  'html[data-tavern-theme="cyber"] .stChatAvatar{border:1px solid var(--st-accent);border-radius:0;box-shadow:0 0 14px rgba(0,229,255,0.45)}',
  'html[data-tavern-theme="cyber"] .stMsgBubble{border:1px solid rgba(0,229,255,0.30);border-radius:2px;letter-spacing:0.05em;line-height:1.7;box-shadow:inset 0 0 22px rgba(0,229,255,0.07)}',
  'html[data-tavern-theme="cyber"] .stMsgChar .stMsgBubble{background:var(--st-msg-char);border-left:2px solid var(--st-accent);color:var(--st-text)}',
  'html[data-tavern-theme="cyber"] .stMsgUser .stMsgBubble{background:var(--st-msg-user);border-color:rgba(255,47,208,0.50);border-right:2px solid var(--st-accent-2);color:#ffe9fb;box-shadow:inset 0 0 22px rgba(255,47,208,0.12),0 0 16px rgba(255,47,208,0.20)}',
  'html[data-tavern-theme="cyber"] .stMsgAvatar{border:1px solid rgba(0,229,255,0.45);border-radius:0}',
  '',
  '/* composer: black well, neon focus ring */',
  'html[data-tavern-theme="cyber"] .stInput{background:rgba(0,0,0,0.74);border:1px solid var(--st-border);border-radius:2px;color:var(--st-text);caret-color:var(--st-accent);letter-spacing:0.05em}',
  'html[data-tavern-theme="cyber"] .stInput::placeholder{color:rgba(95,131,152,0.85)}',
  'html[data-tavern-theme="cyber"] .stInput:focus{border-color:var(--st-accent-2);box-shadow:0 0 0 1px var(--st-accent),0 0 18px rgba(255,47,208,0.35)}',
  'html[data-tavern-theme="cyber"] .stChatInput{background:rgba(0,229,255,0.03);border-top:1px solid var(--st-border)}',
  'html[data-tavern-theme="cyber"] .stBtn{background:rgba(0,229,255,0.06);border:1px solid var(--st-border);border-radius:2px;color:var(--st-accent);font-size:11px;letter-spacing:0.14em;text-transform:uppercase}',
  'html[data-tavern-theme="cyber"] .stBtn:hover{background:rgba(0,229,255,0.16);box-shadow:0 0 16px rgba(0,229,255,0.35)}',
  'html[data-tavern-theme="cyber"] .stBtnPrimary{background:linear-gradient(135deg,rgba(0,229,255,0.92),rgba(0,150,255,0.86));border-color:transparent;color:#02121a;font-weight:700;box-shadow:0 0 20px rgba(0,229,255,0.45)}',
  'html[data-tavern-theme="cyber"] .stBtnPrimary:hover{background:linear-gradient(135deg,#00e5ff,#00a2ff);filter:none;box-shadow:0 0 28px rgba(0,229,255,0.62)}',
  'html[data-tavern-theme="cyber"] .stBtnGhost{border-color:rgba(0,229,255,0.28);color:var(--st-text)}',
  '',
  '/* sections: thin neon outlines, square corners */',
  'html[data-tavern-theme="cyber"] .stSection{background:rgba(0,229,255,0.035);border:1px solid rgba(0,229,255,0.22);border-radius:2px}',
  'html[data-tavern-theme="cyber"] .stSectionHead{background:rgba(0,229,255,0.08);border-bottom:1px solid rgba(0,229,255,0.20);color:var(--st-text);letter-spacing:0.08em}',
  'html[data-tavern-theme="cyber"] .stSectionHead:hover{background:rgba(0,229,255,0.14)}',
  'html[data-tavern-theme="cyber"] .stSectionTitle{font-size:11px;letter-spacing:0.12em;text-transform:uppercase}',
  'html[data-tavern-theme="cyber"] .stSectionHint,',
  'html[data-tavern-theme="cyber"] .stSectionCaret,',
  'html[data-tavern-theme="cyber"] .stLabel,',
  'html[data-tavern-theme="cyber"] .stLiveHint,',
  'html[data-tavern-theme="cyber"] .stLibMeta{color:var(--st-text-dim)}',
  'html[data-tavern-theme="cyber"] .stResultWrap,',
  'html[data-tavern-theme="cyber"] .stWbEntry,',
  'html[data-tavern-theme="cyber"] .stLibItem{background:rgba(0,229,255,0.04);border:1px solid rgba(0,229,255,0.20);border-radius:2px}',
  'html[data-tavern-theme="cyber"] .stCardName{color:#eafeff;text-shadow:0 0 12px rgba(0,229,255,0.55)}',
  'html[data-tavern-theme="cyber"] .stCardTag{background:rgba(255,47,208,0.16);color:#ffe9fb;border-radius:0}',
  '',
  '/* chips, radios, sliders and scrollbars stay square and glowing */',
  'html[data-tavern-theme="cyber"] .stChip{background:rgba(0,0,0,0.55);border:1px solid var(--st-border);border-radius:2px;color:var(--st-text-dim)}',
  'html[data-tavern-theme="cyber"] .stChip:hover{color:var(--st-accent);box-shadow:0 0 12px rgba(0,229,255,0.30)}',
  'html[data-tavern-theme="cyber"] .stChipActive{background:rgba(255,47,208,0.16);border-color:var(--st-accent-2);color:#ffe9fb}',
  'html[data-tavern-theme="cyber"] .stRadio{border:1px solid rgba(0,229,255,0.28);border-radius:2px;color:var(--st-text)}',
  'html[data-tavern-theme="cyber"] .stRadioActive{border-color:var(--st-accent);color:#fff;box-shadow:0 0 12px rgba(0,229,255,0.28)}',
  'html[data-tavern-theme="cyber"] .stSliderVal{background:rgba(0,229,255,0.14);border-radius:0;color:#eafeff}',
  'html[data-tavern-theme="cyber"] .stSwatch{border-radius:0}',
  'html[data-tavern-theme="cyber"] .stTrigger{background:rgba(5,7,14,0.94);border:1px solid var(--st-accent);border-radius:0;color:var(--st-accent);letter-spacing:0.16em;text-transform:uppercase;box-shadow:0 0 18px rgba(0,229,255,0.30)}',
  'html[data-tavern-theme="cyber"] .stRaw,',
  'html[data-tavern-theme="cyber"] .stLivePre,',
  'html[data-tavern-theme="cyber"] .stJsonArea{background:rgba(0,0,0,0.62);border-color:rgba(0,229,255,0.22);border-radius:2px}',
  'html[data-tavern-theme="cyber"] .stEmpty{color:var(--st-text-dim)}',
  'html[data-tavern-theme="cyber"] .stSpinner{border-color:rgba(0,229,255,0.20);border-top-color:var(--st-accent-2)}',
  'html[data-tavern-theme="cyber"] .stPanel ::-webkit-scrollbar{width:8px;height:8px}',
  'html[data-tavern-theme="cyber"] .stPanel ::-webkit-scrollbar-thumb{background:rgba(0,229,255,0.35);border-radius:0}',
  'html[data-tavern-theme="cyber"] .stSlider{accent-color:var(--st-accent)}',
  'html[data-tavern-theme="cyber"] .stAvatarPreview{border:1px solid var(--st-accent);border-radius:0;background:rgba(0,229,255,0.06)}',
  'html[data-tavern-theme="cyber"] .stCardBlockLabel{color:var(--st-text-dim);letter-spacing:0.16em;text-transform:uppercase}',
  'html[data-tavern-theme="cyber"] .stEmptyEmoji{color:rgba(0,229,255,0.45)}',
  'html[data-tavern-theme="cyber"] .stPanel ::-webkit-scrollbar-track{background:rgba(0,229,255,0.05)}',
]

const PARCHMENT_CSS: string[] = [
  '/* Parchment: laid paper grain, serif type, gilt accents like an old folio. */',
  'html[data-tavern-theme="parchment"]{',
  '  --SmartThemeBodyColor:#3a2c1a;',
  '  --SmartThemeEmColor:#8a5a12;',
  '  --SmartThemeQuoteColor:#6b5230;',
  '  --SmartThemeUnderlineColor:#a8761f;',
  '  --SmartThemeBlurTintColor:rgba(214,190,140,0.30);',
  '  --SmartThemeChatTintColor:rgba(246,236,214,0.78);',
  '  --SmartThemeUserMesBlurTintColor:rgba(168,118,31,0.18);',
  '  --SmartThemeBotMesBlurTintColor:rgba(255,252,242,0.55);',
  '  --SmartThemeBlurStrength:4px;',
  '  --SmartThemeShadowColor:rgba(90,66,32,0.28);',
  '  --SmartThemeBorderColor:rgba(150,116,62,0.45);',
  '  --st-accent:#a8761f;',
  '  --st-accent-2:#7a2b1f;',
  '  --st-bg:#e9dcbd;',
  '  --st-panel:linear-gradient(180deg,#f7eed8,#eddfbe);',
  '  --st-panel-2:rgba(255,250,236,0.62);',
  '  --st-text:#3a2c1a;',
  '  --st-text-dim:#7b6440;',
  '  --st-border:rgba(150,116,62,0.45);',
  '  --st-msg-user:linear-gradient(180deg,#ead8ab,#dfc791);',
  '  --st-msg-char:rgba(255,252,242,0.82);',
  '  --st-radius:4px;',
  '  --st-shadow:1px 2px 0 rgba(120,92,48,0.18);',
  '}',
  '',
  '/* shell: paper weave plus an aged vignette on the edges */',
  'html[data-tavern-theme="parchment"] .stPanel{background:var(--st-panel);color:var(--st-text);border-left:1px solid #b99a63;border-radius:0;box-shadow:-18px 0 46px rgba(74,54,26,0.28);font-family:"Iowan Old Style","Palatino Linotype",Georgia,"Songti SC","SimSun",serif;line-height:1.78}',
  'html[data-tavern-theme="parchment"] .stPanel::before{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;mix-blend-mode:multiply;background-image:repeating-linear-gradient(0deg,rgba(120,92,48,0.045) 0 1px,rgba(0,0,0,0) 1px 3px),repeating-linear-gradient(90deg,rgba(120,92,48,0.035) 0 1px,rgba(0,0,0,0) 1px 4px)}',
  'html[data-tavern-theme="parchment"] .stPanel::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:radial-gradient(125% 92% at 50% 45%,rgba(0,0,0,0) 55%,rgba(120,92,48,0.22) 100%)}',
  '@keyframes stParchmentInk{from{opacity:0}to{opacity:1}}',
  '',
  '/* head: rubricated title over a double gilt rule */',
  'html[data-tavern-theme="parchment"] .stPanelHead{background:linear-gradient(180deg,rgba(190,158,98,0.30),rgba(190,158,98,0.06));border-bottom:3px double #b99a63}',
  'html[data-tavern-theme="parchment"] .stPanelTitle{color:#5a3d14;font-weight:700;letter-spacing:0.10em;text-shadow:0 1px 0 rgba(255,252,240,0.85)}',
  'html[data-tavern-theme="parchment"] .stClose{color:#7b6440;border-radius:2px}',
  'html[data-tavern-theme="parchment"] .stClose:hover{background:rgba(168,118,31,0.16);color:#4a3110}',
  '',
  '/* tabs: index tabs ruled by a gilt underline */',
  'html[data-tavern-theme="parchment"] .stTabbar{background:rgba(255,250,236,0.40);border-bottom:1px solid rgba(150,116,62,0.35)}',
  'html[data-tavern-theme="parchment"] .stTab{color:#7b6440;border-radius:3px;letter-spacing:0.06em}',
  'html[data-tavern-theme="parchment"] .stTab:hover{background:rgba(168,118,31,0.12);color:#5a3d14}',
  'html[data-tavern-theme="parchment"] .stTabActive{background:linear-gradient(180deg,rgba(255,252,242,0.92),rgba(232,213,168,0.72));color:#4a3110;box-shadow:inset 0 -2px 0 #a8761f,0 1px 0 rgba(255,252,240,0.70)}',
  '',
  '/* chat: ruled writing paper with an ink vignette */',
  'html[data-tavern-theme="parchment"] .stChatLog{background-image:repeating-linear-gradient(180deg,rgba(0,0,0,0) 0 27px,rgba(120,92,48,0.16) 27px 28px);background-position:0 6px}',
  'html[data-tavern-theme="parchment"] .stChatHead{background:rgba(190,158,98,0.14);border-bottom:1px solid rgba(150,116,62,0.32)}',
  'html[data-tavern-theme="parchment"] .stChatAvatar{border:1px solid #b99a63;border-radius:3px;color:#4a3110;background:linear-gradient(180deg,#e8d5a8,#d9bf8c)}',
  'html[data-tavern-theme="parchment"] .stMsgBubble{border-radius:4px;line-height:1.85;font-size:13.5px;box-shadow:1px 2px 0 rgba(120,92,48,0.18);animation:stParchmentInk 0.35s ease-out}',
  'html[data-tavern-theme="parchment"] .stMsgChar .stMsgBubble{background:var(--st-msg-char);border:1px solid rgba(150,116,62,0.42);border-top-left-radius:2px;color:#3a2c1a}',
  'html[data-tavern-theme="parchment"] .stMsgUser .stMsgBubble{background:var(--st-msg-user);border:1px solid #b99a63;border-top-right-radius:2px;color:#4a3110}',
  'html[data-tavern-theme="parchment"] .stMsgAvatar{border:1px solid #b99a63;border-radius:2px}',
  '',
  '/* composer: laid paper well with a gilt focus rule */',
  'html[data-tavern-theme="parchment"] .stInput{background:rgba(255,252,242,0.88);border:1px solid rgba(150,116,62,0.50);border-radius:3px;color:#3a2c1a;box-shadow:inset 0 1px 3px rgba(120,92,48,0.22)}',
  'html[data-tavern-theme="parchment"] .stInput::placeholder{color:rgba(123,100,64,0.60)}',
  'html[data-tavern-theme="parchment"] .stInput:focus{border-color:#a8761f;box-shadow:inset 0 1px 3px rgba(120,92,48,0.24),0 0 0 2px rgba(168,118,31,0.25)}',
  'html[data-tavern-theme="parchment"] .stChatInput{background:rgba(190,158,98,0.10);border-top:1px solid rgba(150,116,62,0.35)}',
  'html[data-tavern-theme="parchment"] .stBtn{background:linear-gradient(180deg,#f4e8cb,#e4d2a6);border:1px solid #b99a63;border-radius:3px;color:#4a3110;letter-spacing:0.04em}',
  'html[data-tavern-theme="parchment"] .stBtn:hover{background:linear-gradient(180deg,#f9efda,#ead9b0)}',
  'html[data-tavern-theme="parchment"] .stBtnPrimary{background:linear-gradient(180deg,#c6952f,#a8761f);border-color:#8a5a12;color:#fff8e6;text-shadow:0 1px 0 rgba(90,60,10,0.45)}',
  'html[data-tavern-theme="parchment"] .stBtnPrimary:hover{background:linear-gradient(180deg,#d3a23c,#b5801f);filter:none}',
  'html[data-tavern-theme="parchment"] .stBtnGhost{border-color:rgba(150,116,62,0.45);color:#7b6440}',
  '',
  '/* sections: cream leaves marked by a gilt margin rule */',
  'html[data-tavern-theme="parchment"] .stSection{background:rgba(255,250,236,0.64);border:1px solid rgba(150,116,62,0.40);border-left:3px solid #a8761f;border-radius:3px;box-shadow:0 1px 0 rgba(255,252,240,0.85)}',
  'html[data-tavern-theme="parchment"] .stSectionHead{background:rgba(190,158,98,0.20);border-bottom:1px solid rgba(150,116,62,0.28);color:#4a3110}',
  'html[data-tavern-theme="parchment"] .stSectionHead:hover{background:rgba(190,158,98,0.30)}',
  'html[data-tavern-theme="parchment"] .stSectionTitle{letter-spacing:0.06em}',
  'html[data-tavern-theme="parchment"] .stSectionHint,',
  'html[data-tavern-theme="parchment"] .stSectionCaret,',
  'html[data-tavern-theme="parchment"] .stLabel,',
  'html[data-tavern-theme="parchment"] .stLiveHint,',
  'html[data-tavern-theme="parchment"] .stLibMeta{color:#7b6440}',
  'html[data-tavern-theme="parchment"] .stCheck,',
  'html[data-tavern-theme="parchment"] .stRadio{color:#5a4326}',
  'html[data-tavern-theme="parchment"] .stResultWrap,',
  'html[data-tavern-theme="parchment"] .stWbEntry,',
  'html[data-tavern-theme="parchment"] .stLibItem{background:rgba(255,250,236,0.66);border:1px solid rgba(150,116,62,0.35);border-radius:3px}',
  'html[data-tavern-theme="parchment"] .stCardName{color:#4a3110;letter-spacing:0.04em}',
  'html[data-tavern-theme="parchment"] .stCardTag{background:rgba(168,118,31,0.18);color:#5a3d14;border-radius:2px}',
  '',
  '/* chips, radios, sliders and scrollbars: wax, brass and ink */',
  'html[data-tavern-theme="parchment"] .stChip{background:rgba(255,252,242,0.70);border:1px solid rgba(150,116,62,0.45);border-radius:2px;color:#5a4326}',
  'html[data-tavern-theme="parchment"] .stChip:hover{border-color:#a8761f;color:#4a3110}',
  'html[data-tavern-theme="parchment"] .stChipActive{background:linear-gradient(180deg,#d8b96a,#c19a3c);border-color:#8a5a12;color:#3a2a08}',
  'html[data-tavern-theme="parchment"] .stRadio{border:1px solid rgba(150,116,62,0.45);border-radius:2px;color:#5a4326}',
  'html[data-tavern-theme="parchment"] .stRadioActive{border-color:#a8761f;background:rgba(168,118,31,0.16);color:#3a2a08}',
  'html[data-tavern-theme="parchment"] .stSliderVal{background:rgba(168,118,31,0.20);border-radius:2px;color:#4a3110}',
  'html[data-tavern-theme="parchment"] .stSwatch{border-radius:2px;box-shadow:0 1px 0 rgba(255,252,240,0.90)}',
  'html[data-tavern-theme="parchment"] .stTrigger{background:linear-gradient(180deg,#f4e8cb,#e0cda0);border:1px solid #b99a63;border-radius:3px;color:#5a3d14;letter-spacing:0.08em}',
  'html[data-tavern-theme="parchment"] .stRaw,',
  'html[data-tavern-theme="parchment"] .stLivePre,',
  'html[data-tavern-theme="parchment"] .stJsonArea{background:rgba(255,252,242,0.78);border-color:rgba(150,116,62,0.38);border-radius:3px;color:#4a3a22}',
  'html[data-tavern-theme="parchment"] .stNotice{background:#f3e3bd;border-color:#c19a3c;color:#7a4a10}',
  'html[data-tavern-theme="parchment"] .stEmpty{color:#7b6440}',
  'html[data-tavern-theme="parchment"] .stSpinner{border-color:rgba(150,116,62,0.25);border-top-color:#a8761f}',
  'html[data-tavern-theme="parchment"] .stPanel ::-webkit-scrollbar{width:10px;height:10px}',
  'html[data-tavern-theme="parchment"] .stPanel ::-webkit-scrollbar-thumb{background:rgba(150,116,62,0.45);border-radius:0}',
  'html[data-tavern-theme="parchment"] .stPanel ::-webkit-scrollbar-track{background:rgba(190,158,98,0.14)}',
]

const SAKURA_CSS: string[] = [
  '/* Sakura: pink and white translucency with petals drifting down the panel. */',
  'html[data-tavern-theme="sakura"]{',
  '  --SmartThemeBodyColor:#4a3540;',
  '  --SmartThemeEmColor:#d94f86;',
  '  --SmartThemeQuoteColor:#a2688a;',
  '  --SmartThemeUnderlineColor:#ff8fbb;',
  '  --SmartThemeBlurTintColor:rgba(255,214,229,0.35);',
  '  --SmartThemeChatTintColor:rgba(255,248,251,0.72);',
  '  --SmartThemeUserMesBlurTintColor:rgba(255,143,187,0.24);',
  '  --SmartThemeBotMesBlurTintColor:rgba(255,255,255,0.65);',
  '  --SmartThemeBlurStrength:12px;',
  '  --SmartThemeShadowColor:rgba(214,128,164,0.28);',
  '  --SmartThemeBorderColor:rgba(255,168,199,0.55);',
  '  --st-accent:#ff7aa8;',
  '  --st-accent-2:#c86fa8;',
  '  --st-bg:#fff4f8;',
  '  --st-panel:linear-gradient(180deg,rgba(255,251,253,0.95),rgba(255,240,246,0.92));',
  '  --st-panel-2:rgba(255,255,255,0.75);',
  '  --st-text:#4a3540;',
  '  --st-text-dim:#9c7c8b;',
  '  --st-border:rgba(255,168,199,0.55);',
  '  --st-msg-user:linear-gradient(135deg,#ffa8c8,#ff7aa8);',
  '  --st-msg-char:rgba(255,255,255,0.90);',
  '  --st-radius:18px;',
  '  --st-glow:0 8px 20px rgba(214,128,164,0.18);',
  '}',
  '',
  '/* shell: frosted blossom glass with a petal shower */',
  'html[data-tavern-theme="sakura"] .stPanel{background:var(--st-panel);color:var(--st-text);border-left:1px solid var(--st-border);border-radius:22px 0 0 22px;box-shadow:-18px 0 48px rgba(214,128,164,0.28),inset 0 1px 0 rgba(255,255,255,0.92);font-family:"Hiragino Sans","PingFang SC","Microsoft YaHei",system-ui,sans-serif}',
  'html[data-tavern-theme="sakura"] .stPanel::before{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;opacity:0.55;background-image:radial-gradient(circle at 22% 18%,rgba(255,168,199,0.85) 0 3px,rgba(0,0,0,0) 4px),radial-gradient(circle at 68% 62%,rgba(255,205,224,0.90) 0 2.5px,rgba(0,0,0,0) 3.5px),radial-gradient(circle at 42% 86%,rgba(255,143,187,0.70) 0 3.5px,rgba(0,0,0,0) 4.5px);background-size:180px 200px;background-repeat:repeat;animation:stSakuraFall 18s linear infinite}',
  'html[data-tavern-theme="sakura"] .stPanel::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:radial-gradient(110% 60% at 80% 0%,rgba(255,196,220,0.42),transparent 66%),radial-gradient(90% 55% at 0% 100%,rgba(255,224,236,0.50),transparent 70%)}',
  '@keyframes stSakuraFall{from{background-position:0 0}to{background-position:0 200px}}',
  '',
  '/* head: blossom banner with a petal underline */',
  'html[data-tavern-theme="sakura"] .stPanelHead{background:linear-gradient(90deg,rgba(255,214,229,0.78),rgba(255,255,255,0.35));border-bottom:1px solid rgba(255,168,199,0.50)}',
  'html[data-tavern-theme="sakura"] .stPanelTitle{color:#c2477c;font-weight:600;letter-spacing:0.04em;text-shadow:0 1px 0 #fff}',
  'html[data-tavern-theme="sakura"] .stClose{color:#c98aa6;border-radius:999px}',
  'html[data-tavern-theme="sakura"] .stClose:hover{background:rgba(255,168,199,0.28);color:#a8305f}',
  '',
  '/* tabs: petal pills, the active one filled */',
  'html[data-tavern-theme="sakura"] .stTabbar{background:rgba(255,255,255,0.42);border-bottom:1px solid rgba(255,168,199,0.40)}',
  'html[data-tavern-theme="sakura"] .stTab{color:#9c7c8b;border-radius:999px;transition:background 0.20s ease,color 0.20s ease}',
  'html[data-tavern-theme="sakura"] .stTab:hover{background:rgba(255,168,199,0.20);color:#c2477c}',
  'html[data-tavern-theme="sakura"] .stTabActive{background:linear-gradient(135deg,#ffb3cd,#ff8ab4);color:#fff;box-shadow:0 6px 16px rgba(255,122,168,0.40)}',
  '',
  '/* chat: soft blossom wash behind the transcript */',
  'html[data-tavern-theme="sakura"] .stChatLog{background-image:radial-gradient(120% 70% at 50% 0%,rgba(255,214,229,0.55),transparent 70%),radial-gradient(80% 50% at 90% 100%,rgba(255,196,220,0.35),transparent 75%)}',
  'html[data-tavern-theme="sakura"] .stChatHead{background:rgba(255,255,255,0.45);border-bottom:1px solid rgba(255,168,199,0.40)}',
  'html[data-tavern-theme="sakura"] .stChatAvatar{border:2px solid rgba(255,255,255,0.90);box-shadow:0 6px 16px rgba(214,128,164,0.30)}',
  'html[data-tavern-theme="sakura"] .stMsgBubble{border:1px solid rgba(255,168,199,0.45);border-radius:18px;line-height:1.75;box-shadow:var(--st-glow)}',
  'html[data-tavern-theme="sakura"] .stMsgChar .stMsgBubble{background:var(--st-msg-char);border-top-left-radius:6px;color:var(--st-text)}',
  'html[data-tavern-theme="sakura"] .stMsgUser .stMsgBubble{background:var(--st-msg-user);border-color:rgba(255,255,255,0.65);border-top-right-radius:6px;color:#fff;box-shadow:0 10px 22px rgba(255,122,168,0.35)}',
  'html[data-tavern-theme="sakura"] .stMsgAvatar{border:2px solid rgba(255,255,255,0.85)}',
  '',
  '/* composer: white petal well with a pink halo */',
  'html[data-tavern-theme="sakura"] .stInput{background:rgba(255,255,255,0.88);border:1px solid rgba(255,168,199,0.60);border-radius:14px;color:var(--st-text);box-shadow:inset 0 1px 2px rgba(214,128,164,0.14)}',
  'html[data-tavern-theme="sakura"] .stInput::placeholder{color:rgba(156,124,139,0.70)}',
  'html[data-tavern-theme="sakura"] .stInput:focus{border-color:var(--st-accent);box-shadow:0 0 0 3px rgba(255,168,199,0.35)}',
  'html[data-tavern-theme="sakura"] .stChatInput{background:rgba(255,255,255,0.40);border-top:1px solid rgba(255,168,199,0.40)}',
  'html[data-tavern-theme="sakura"] .stBtn{background:rgba(255,255,255,0.82);border:1px solid rgba(255,168,199,0.60);border-radius:999px;color:#c2477c;transition:box-shadow 0.18s ease,transform 0.18s ease}',
  'html[data-tavern-theme="sakura"] .stBtn:hover{background:#fff;transform:translateY(-1px);box-shadow:0 6px 16px rgba(255,122,168,0.25)}',
  'html[data-tavern-theme="sakura"] .stBtnPrimary{background:linear-gradient(135deg,#ff9dc0,#ff7aa8);border-color:transparent;color:#fff;box-shadow:0 8px 20px rgba(255,122,168,0.42)}',
  'html[data-tavern-theme="sakura"] .stBtnPrimary:hover{background:linear-gradient(135deg,#ffabcd,#ff8ab4);filter:none}',
  'html[data-tavern-theme="sakura"] .stBtnGhost{border-color:rgba(255,168,199,0.55);color:#c98aa6}',
  '',
  '/* sections: white blossom cards on the pink wash */',
  'html[data-tavern-theme="sakura"] .stSection{background:rgba(255,255,255,0.74);border:1px solid rgba(255,168,199,0.45);border-radius:16px;box-shadow:0 8px 22px rgba(214,128,164,0.14)}',
  'html[data-tavern-theme="sakura"] .stSectionHead{background:linear-gradient(90deg,rgba(255,214,229,0.62),rgba(255,255,255,0.20));color:#7a455c}',
  'html[data-tavern-theme="sakura"] .stSectionHead:hover{background:linear-gradient(90deg,rgba(255,200,220,0.75),rgba(255,255,255,0.30))}',
  'html[data-tavern-theme="sakura"] .stSectionHint,',
  'html[data-tavern-theme="sakura"] .stSectionCaret,',
  'html[data-tavern-theme="sakura"] .stLabel,',
  'html[data-tavern-theme="sakura"] .stLiveHint,',
  'html[data-tavern-theme="sakura"] .stLibMeta{color:#9c7c8b}',
  'html[data-tavern-theme="sakura"] .stCheck,',
  'html[data-tavern-theme="sakura"] .stRadio{color:#7a5b69}',
  'html[data-tavern-theme="sakura"] .stResultWrap,',
  'html[data-tavern-theme="sakura"] .stWbEntry,',
  'html[data-tavern-theme="sakura"] .stLibItem{background:rgba(255,255,255,0.78);border:1px solid rgba(255,168,199,0.38);border-radius:14px}',
  'html[data-tavern-theme="sakura"] .stCardName{color:#b8406f;text-shadow:0 2px 10px rgba(255,168,199,0.55)}',
  'html[data-tavern-theme="sakura"] .stCardTag{background:rgba(255,168,199,0.28);color:#a8305f}',
  '',
  '/* chips, radios, sliders and scrollbars stay light and round */',
  'html[data-tavern-theme="sakura"] .stChip{background:rgba(255,255,255,0.80);border:1px solid rgba(255,168,199,0.55);color:#9c7c8b}',
  'html[data-tavern-theme="sakura"] .stChip:hover{border-color:var(--st-accent);color:#c2477c}',
  'html[data-tavern-theme="sakura"] .stChipActive{background:linear-gradient(135deg,#ffb3cd,#ff8ab4);border-color:transparent;color:#fff}',
  'html[data-tavern-theme="sakura"] .stRadio{border:1px solid rgba(255,168,199,0.55);color:#7a5b69}',
  'html[data-tavern-theme="sakura"] .stRadioActive{border-color:var(--st-accent);background:rgba(255,168,199,0.22);color:#a8305f}',
  'html[data-tavern-theme="sakura"] .stSliderVal{background:rgba(255,168,199,0.28);color:#a8305f}',
  'html[data-tavern-theme="sakura"] .stSwatch{box-shadow:0 4px 10px rgba(214,128,164,0.30)}',
  'html[data-tavern-theme="sakura"] .stTrigger{background:linear-gradient(135deg,rgba(255,255,255,0.94),rgba(255,232,241,0.94));border:1px solid rgba(255,168,199,0.70);color:#c2477c;box-shadow:0 8px 20px rgba(214,128,164,0.28)}',
  'html[data-tavern-theme="sakura"] .stRaw,',
  'html[data-tavern-theme="sakura"] .stLivePre,',
  'html[data-tavern-theme="sakura"] .stJsonArea{background:rgba(255,255,255,0.78);border-color:rgba(255,168,199,0.40);border-radius:12px;color:#5c4550}',
  'html[data-tavern-theme="sakura"] .stNotice{background:#fff0f5;border-color:#ffb3cd;color:#a8305f}',
  'html[data-tavern-theme="sakura"] .stEmpty{color:#9c7c8b}',
  'html[data-tavern-theme="sakura"] .stSpinner{border-color:rgba(255,168,199,0.35);border-top-color:var(--st-accent)}',
  'html[data-tavern-theme="sakura"] .stPanel ::-webkit-scrollbar{width:10px;height:10px}',
  'html[data-tavern-theme="sakura"] .stPanel ::-webkit-scrollbar-thumb{background:rgba(255,168,199,0.60);border-radius:999px}',
  'html[data-tavern-theme="sakura"] .stPanel ::-webkit-scrollbar-track{background:rgba(255,240,246,0.60)}',
]

const TERMINAL_CSS: string[] = [
  '/* Terminal: pure black, phosphor green monospace, square corners, no shadows. */',
  'html[data-tavern-theme="terminal"]{',
  '  --SmartThemeBodyColor:#c4ffd4;',
  '  --SmartThemeEmColor:#39ff88;',
  '  --SmartThemeQuoteColor:#6fbf8c;',
  '  --SmartThemeUnderlineColor:#39ff88;',
  '  --SmartThemeBlurTintColor:rgba(0,0,0,0.85);',
  '  --SmartThemeChatTintColor:rgba(0,0,0,0.92);',
  '  --SmartThemeUserMesBlurTintColor:rgba(57,255,136,0.10);',
  '  --SmartThemeBotMesBlurTintColor:rgba(0,255,120,0.05);',
  '  --SmartThemeBlurStrength:0px;',
  '  --SmartThemeShadowColor:rgba(0,0,0,0.90);',
  '  --SmartThemeBorderColor:#1f5c33;',
  '  --st-accent:#39ff88;',
  '  --st-accent-2:#1f5c33;',
  '  --st-bg:#000000;',
  '  --st-panel:#000000;',
  '  --st-panel-2:#050b06;',
  '  --st-text:#c4ffd4;',
  '  --st-text-dim:#4f9c68;',
  '  --st-border:#1f5c33;',
  '  --st-msg-user:rgba(57,255,136,0.08);',
  '  --st-msg-char:rgba(0,0,0,0);',
  '  --st-radius:0;',
  '  --st-shadow:none;',
  '}',
  '',
  '/* shell: black glass with a faint CRT line mask, nothing rounded or glowing */',
  'html[data-tavern-theme="terminal"] .stPanel{background:#000000;color:var(--st-text);border-left:2px solid var(--st-accent-2);border-radius:0;box-shadow:none;font-family:"Cascadia Mono","Consolas","DejaVu Sans Mono","Microsoft YaHei",monospace;font-size:13px;line-height:1.7}',
  'html[data-tavern-theme="terminal"] .stPanel::before{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background-image:repeating-linear-gradient(180deg,rgba(57,255,136,0.035) 0 1px,rgba(0,0,0,0) 1px 3px)}',
  'html[data-tavern-theme="terminal"] .stPanel::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:none}',
  '@keyframes stTerminalBlink{0%,49%{opacity:1}50%,100%{opacity:0}}',
  '',
  '/* head: a prompt line with a blinking block cursor */',
  'html[data-tavern-theme="terminal"] .stPanelHead{background:#000000;border-bottom:1px dashed var(--st-accent-2);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stPanelTitle{color:var(--st-accent);font-weight:700;letter-spacing:0.14em;text-transform:uppercase}',
  'html[data-tavern-theme="terminal"] .stPanelTitle::after{content:"_";margin-left:2px;animation:stTerminalBlink 1.1s steps(1,end) infinite}',
  'html[data-tavern-theme="terminal"] .stClose{color:var(--st-text-dim);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stClose:hover{background:#07160c;color:var(--st-accent)}',
  '',
  '/* tabs: bracketed command words, the active one underscored */',
  'html[data-tavern-theme="terminal"] .stTabbar{background:#000000;border-bottom:1px solid var(--st-accent-2);border-radius:0;gap:2px}',
  'html[data-tavern-theme="terminal"] .stTab{color:var(--st-text-dim);border-radius:0;letter-spacing:0.08em}',
  'html[data-tavern-theme="terminal"] .stTab::before{content:"[ "}',
  'html[data-tavern-theme="terminal"] .stTab::after{content:" ]"}',
  'html[data-tavern-theme="terminal"] .stTab:hover{background:#07160c;color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stTabActive{background:#0a1a0f;color:var(--st-accent);box-shadow:inset 0 -2px 0 var(--st-accent)}',
  '',
  '/* chat: bare black screen with the CRT mask only */',
  'html[data-tavern-theme="terminal"] .stChatLog{background:#000000;background-image:repeating-linear-gradient(180deg,rgba(57,255,136,0.03) 0 1px,rgba(0,0,0,0) 1px 4px)}',
  'html[data-tavern-theme="terminal"] .stChatHead{background:#000000;border-bottom:1px solid var(--st-accent-2);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stChatAvatar{border:1px solid var(--st-accent-2);border-radius:0;background:#050b06;color:var(--st-accent);box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stMsgBubble{border-radius:0;box-shadow:none;line-height:1.65;padding:8px 10px;font-size:13px}',
  'html[data-tavern-theme="terminal"] .stMsgChar .stMsgBubble{background:transparent;border:1px solid var(--st-accent-2);color:var(--st-text)}',
  'html[data-tavern-theme="terminal"] .stMsgChar .stMsgBubble::before{content:"> ";color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stMsgUser .stMsgBubble{background:#07160c;border:1px solid #2b7a45;color:#d8ffe4}',
  'html[data-tavern-theme="terminal"] .stMsgUser .stMsgBubble::before{content:"$ ";color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stMsgAvatar{border:1px solid var(--st-accent-2);border-radius:0}',
  '',
  '/* composer: a bare command line, focus is a hard outline, not a glow */',
  'html[data-tavern-theme="terminal"] .stInput{background:#000000;border:1px solid var(--st-accent-2);border-radius:0;color:var(--st-text);caret-color:var(--st-accent);box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stInput::placeholder{color:#3d7a52}',
  'html[data-tavern-theme="terminal"] .stInput:focus{outline:1px solid var(--st-accent);outline-offset:-1px;border-color:var(--st-accent);box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stChatInput{background:#000000;border-top:1px solid var(--st-accent-2);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stBtn{background:#000000;border:1px solid var(--st-accent-2);border-radius:0;color:var(--st-accent);font-size:11px;letter-spacing:0.08em;text-transform:uppercase;box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stBtn:hover{background:#07160c;border-color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stBtnPrimary{background:var(--st-accent);border-color:var(--st-accent);color:#001a09;font-weight:700;box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stBtnPrimary:hover{background:#5cffa0;filter:none}',
  'html[data-tavern-theme="terminal"] .stBtnGhost{border-color:var(--st-accent-2);color:var(--st-text-dim)}',
  '',
  '/* sections: dashed boxes that look like plain text frames */',
  'html[data-tavern-theme="terminal"] .stSection{background:#000000;border:1px dashed var(--st-accent-2);border-radius:0;box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stSectionHead{background:#050b06;color:var(--st-text);border-radius:0;border-bottom:1px solid var(--st-accent-2)}',
  'html[data-tavern-theme="terminal"] .stSectionHead::before{content:"> "}',
  'html[data-tavern-theme="terminal"] .stSectionHead:hover{background:#0a1a0f}',
  'html[data-tavern-theme="terminal"] .stSectionTitle{letter-spacing:0.06em}',
  'html[data-tavern-theme="terminal"] .stSectionHint,',
  'html[data-tavern-theme="terminal"] .stSectionCaret,',
  'html[data-tavern-theme="terminal"] .stLabel,',
  'html[data-tavern-theme="terminal"] .stLiveHint,',
  'html[data-tavern-theme="terminal"] .stLibMeta{color:var(--st-text-dim)}',
  'html[data-tavern-theme="terminal"] .stCheck,',
  'html[data-tavern-theme="terminal"] .stRadio{color:var(--st-text);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stResultWrap,',
  'html[data-tavern-theme="terminal"] .stWbEntry,',
  'html[data-tavern-theme="terminal"] .stLibItem{background:#000000;border:1px solid var(--st-accent-2);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stCardName{color:var(--st-accent);letter-spacing:0.06em}',
  'html[data-tavern-theme="terminal"] .stCardTag{background:#050b06;color:var(--st-text-dim);border-radius:0}',
  '',
  '/* chips, radios, sliders and scrollbars: square, outlined, unlit */',
  'html[data-tavern-theme="terminal"] .stChip{background:#000000;border:1px solid var(--st-accent-2);border-radius:0;color:var(--st-text-dim)}',
  'html[data-tavern-theme="terminal"] .stChip:hover{border-color:var(--st-accent);color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stChipActive{background:#0a1a0f;border-color:var(--st-accent);color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stRadio{border:1px solid var(--st-accent-2);border-radius:0;color:var(--st-text)}',
  'html[data-tavern-theme="terminal"] .stRadioActive{border-color:var(--st-accent);background:#0a1a0f;color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stSliderVal{background:#050b06;border-radius:0;color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stSwatch{border-radius:0;box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stTrigger{background:#000000;border:1px solid var(--st-accent);border-radius:0;color:var(--st-accent);letter-spacing:0.10em;text-transform:uppercase;box-shadow:none}',
  'html[data-tavern-theme="terminal"] .stRaw,',
  'html[data-tavern-theme="terminal"] .stLivePre,',
  'html[data-tavern-theme="terminal"] .stJsonArea{background:#000000;border-color:var(--st-accent-2);border-radius:0;color:var(--st-text)}',
  'html[data-tavern-theme="terminal"] .stRawSummary{color:var(--st-text-dim)}',
  'html[data-tavern-theme="terminal"] .stNotice{background:#0a1a0f;border-color:var(--st-accent);border-radius:0;color:var(--st-accent)}',
  'html[data-tavern-theme="terminal"] .stEmpty{color:var(--st-text-dim)}',
  'html[data-tavern-theme="terminal"] .stSpinner{border-color:var(--st-accent-2);border-top-color:var(--st-accent);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stPanel ::-webkit-scrollbar{width:8px;height:8px}',
  'html[data-tavern-theme="terminal"] .stPanel ::-webkit-scrollbar-thumb{background:var(--st-accent-2);border-radius:0}',
  'html[data-tavern-theme="terminal"] .stPanel ::-webkit-scrollbar-track{background:#000000}',
]

const NOCTURNE_CSS: string[] = [
  '/* Nocturne: deep indigo dusk, low saturation, unhurried reading typography. */',
  'html[data-tavern-theme="nocturne"]{',
  '  --SmartThemeBodyColor:#d3d8ea;',
  '  --SmartThemeEmColor:#a9b2e0;',
  '  --SmartThemeQuoteColor:#8f97bf;',
  '  --SmartThemeUnderlineColor:#7c86b8;',
  '  --SmartThemeBlurTintColor:rgba(60,72,120,0.24);',
  '  --SmartThemeChatTintColor:rgba(18,22,38,0.72);',
  '  --SmartThemeUserMesBlurTintColor:rgba(96,110,180,0.22);',
  '  --SmartThemeBotMesBlurTintColor:rgba(40,48,80,0.28);',
  '  --SmartThemeBlurStrength:14px;',
  '  --SmartThemeShadowColor:rgba(4,6,16,0.55);',
  '  --SmartThemeBorderColor:rgba(126,138,190,0.28);',
  '  --st-accent:#8b93c9;',
  '  --st-accent-2:#6f7bb8;',
  '  --st-bg:#0b0f1d;',
  '  --st-panel:linear-gradient(180deg,#161c31,#101425 62%,#0d1120);',
  '  --st-panel-2:rgba(255,255,255,0.045);',
  '  --st-text:#d3d8ea;',
  '  --st-text-dim:#7a83a6;',
  '  --st-border:rgba(126,138,190,0.28);',
  '  --st-msg-user:linear-gradient(135deg,#3b4478,#2b3159);',
  '  --st-msg-char:rgba(255,255,255,0.05);',
  '  --st-radius:14px;',
  '  --st-glow:0 14px 38px rgba(3,5,14,0.55);',
  '}',
  '',
  '/* shell: a deep gradient sheet with a faint starfield and a breathing glow */',
  'html[data-tavern-theme="nocturne"] .stPanel{background:var(--st-panel);color:var(--st-text);border-left:1px solid rgba(126,138,190,0.22);border-radius:0;box-shadow:-24px 0 70px rgba(3,5,14,0.70),inset 0 1px 0 rgba(255,255,255,0.06);font-family:"Iowan Old Style",Georgia,"Songti SC","Times New Roman",serif;line-height:1.85}',
  'html[data-tavern-theme="nocturne"] .stPanel::before{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;opacity:0.50;background-image:radial-gradient(1.5px 1.5px at 18% 22%,rgba(200,214,255,0.55),rgba(0,0,0,0) 65%),radial-gradient(1.5px 1.5px at 74% 44%,rgba(180,196,255,0.45),rgba(0,0,0,0) 65%),radial-gradient(1.5px 1.5px at 38% 78%,rgba(210,220,255,0.38),rgba(0,0,0,0) 65%);background-size:220px 240px;background-repeat:repeat}',
  'html[data-tavern-theme="nocturne"] .stPanel::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:radial-gradient(90% 55% at 78% 4%,rgba(120,136,220,0.16),transparent 68%),radial-gradient(80% 50% at 12% 96%,rgba(94,80,168,0.14),transparent 70%);animation:stNocturneBreath 12s ease-in-out infinite}',
  '@keyframes stNocturneBreath{0%,100%{opacity:0.75}50%{opacity:1}}',
  '',
  '/* head: quiet gradient band, wide tracking, no hard rule */',
  'html[data-tavern-theme="nocturne"] .stPanelHead{background:linear-gradient(180deg,rgba(126,138,190,0.14),transparent);border-bottom:1px solid var(--st-border)}',
  'html[data-tavern-theme="nocturne"] .stPanelTitle{color:#e2e6f6;font-weight:600;letter-spacing:0.08em}',
  'html[data-tavern-theme="nocturne"] .stClose{color:var(--st-text-dim);border-radius:8px}',
  'html[data-tavern-theme="nocturne"] .stClose:hover{background:rgba(255,255,255,0.07);color:#e2e6f6}',
  '',
  '/* tabs: no pills, just a slowly lit underline under the active label */',
  'html[data-tavern-theme="nocturne"] .stTabbar{background:transparent;border-bottom:1px solid var(--st-border);gap:2px}',
  'html[data-tavern-theme="nocturne"] .stTab{color:var(--st-text-dim);border-radius:0;letter-spacing:0.06em;padding:8px 14px}',
  'html[data-tavern-theme="nocturne"] .stTab:hover{color:#cfd5ec;background:rgba(139,147,201,0.08)}',
  'html[data-tavern-theme="nocturne"] .stTabActive{background:transparent;color:#eef1fb;box-shadow:inset 0 -1px 0 var(--st-accent);text-shadow:0 0 14px rgba(139,147,201,0.55)}',
  '',
  '/* chat: dusk wash with generous breathing room */',
  'html[data-tavern-theme="nocturne"] .stChatLog{background-image:linear-gradient(180deg,rgba(139,147,201,0.06),rgba(0,0,0,0) 45%);gap:14px}',
  'html[data-tavern-theme="nocturne"] .stChatHead{background:rgba(255,255,255,0.02);border-bottom:1px solid var(--st-border)}',
  'html[data-tavern-theme="nocturne"] .stChatAvatar{border:1px solid rgba(126,138,190,0.35);box-shadow:0 8px 22px rgba(3,5,14,0.55)}',
  'html[data-tavern-theme="nocturne"] .stMsgBubble{border:1px solid rgba(255,255,255,0.07);border-radius:14px;line-height:1.9;font-size:13.5px;box-shadow:var(--st-glow)}',
  'html[data-tavern-theme="nocturne"] .stMsgChar .stMsgBubble{background:var(--st-msg-char);border-top-left-radius:4px;color:var(--st-text)}',
  'html[data-tavern-theme="nocturne"] .stMsgUser .stMsgBubble{background:var(--st-msg-user);border-color:rgba(139,147,201,0.30);border-top-right-radius:4px;color:#eef1fb}',
  'html[data-tavern-theme="nocturne"] .stMsgAvatar{border:1px solid rgba(126,138,190,0.30)}',
  '',
  '/* composer: low-contrast well, focus is a soft widening ring */',
  'html[data-tavern-theme="nocturne"] .stInput{background:rgba(255,255,255,0.045);border:1px solid var(--st-border);border-radius:10px;color:var(--st-text);font-family:"Segoe UI","PingFang SC",system-ui,sans-serif}',
  'html[data-tavern-theme="nocturne"] .stInput::placeholder{color:rgba(122,131,166,0.75)}',
  'html[data-tavern-theme="nocturne"] .stInput:focus{border-color:var(--st-accent);box-shadow:0 0 0 3px rgba(139,147,201,0.18)}',
  'html[data-tavern-theme="nocturne"] .stChatInput{background:rgba(255,255,255,0.02);border-top:1px solid var(--st-border)}',
  'html[data-tavern-theme="nocturne"] .stBtn{background:rgba(255,255,255,0.05);border:1px solid var(--st-border);border-radius:10px;color:var(--st-text);font-family:"Segoe UI","PingFang SC",system-ui,sans-serif;font-size:12px}',
  'html[data-tavern-theme="nocturne"] .stBtn:hover{background:rgba(255,255,255,0.09);border-color:rgba(139,147,201,0.45)}',
  'html[data-tavern-theme="nocturne"] .stBtnPrimary{background:linear-gradient(135deg,#5b6499,#454d80);border-color:rgba(139,147,201,0.45);color:#f2f4fd;box-shadow:0 10px 26px rgba(3,5,14,0.45)}',
  'html[data-tavern-theme="nocturne"] .stBtnPrimary:hover{background:linear-gradient(135deg,#68719f,#4d5590);filter:none}',
  'html[data-tavern-theme="nocturne"] .stBtnGhost{border-color:var(--st-border);color:var(--st-text-dim)}',
  '',
  '/* sections: quiet cards that recede into the dusk */',
  'html[data-tavern-theme="nocturne"] .stSection{background:rgba(255,255,255,0.035);border:1px solid var(--st-border);border-radius:12px;box-shadow:0 12px 30px rgba(3,5,14,0.35)}',
  'html[data-tavern-theme="nocturne"] .stSectionHead{background:linear-gradient(180deg,rgba(139,147,201,0.12),rgba(139,147,201,0.02));color:var(--st-text)}',
  'html[data-tavern-theme="nocturne"] .stSectionHead:hover{background:rgba(139,147,201,0.14)}',
  'html[data-tavern-theme="nocturne"] .stSectionTitle{letter-spacing:0.05em;font-weight:600}',
  'html[data-tavern-theme="nocturne"] .stSectionHint,',
  'html[data-tavern-theme="nocturne"] .stSectionCaret,',
  'html[data-tavern-theme="nocturne"] .stLabel,',
  'html[data-tavern-theme="nocturne"] .stLiveHint,',
  'html[data-tavern-theme="nocturne"] .stLibMeta{color:var(--st-text-dim)}',
  'html[data-tavern-theme="nocturne"] .stCheck,',
  'html[data-tavern-theme="nocturne"] .stRadio{color:#b9c0da}',
  'html[data-tavern-theme="nocturne"] .stResultWrap,',
  'html[data-tavern-theme="nocturne"] .stWbEntry,',
  'html[data-tavern-theme="nocturne"] .stLibItem{background:rgba(255,255,255,0.03);border:1px solid var(--st-border);border-radius:12px}',
  'html[data-tavern-theme="nocturne"] .stCardName{color:#eef1fb;letter-spacing:0.04em;font-weight:600}',
  'html[data-tavern-theme="nocturne"] .stCardTag{background:rgba(139,147,201,0.18);color:#c6cce6}',
  '',
  '/* chips, radios, sliders and scrollbars: muted indigo, never loud */',
  'html[data-tavern-theme="nocturne"] .stChip{background:rgba(255,255,255,0.04);border:1px solid var(--st-border);color:var(--st-text-dim)}',
  'html[data-tavern-theme="nocturne"] .stChip:hover{border-color:rgba(139,147,201,0.50);color:var(--st-text)}',
  'html[data-tavern-theme="nocturne"] .stChipActive{background:rgba(139,147,201,0.22);border-color:var(--st-accent);color:#eef1fb}',
  'html[data-tavern-theme="nocturne"] .stRadio{border:1px solid var(--st-border);color:#b9c0da}',
  'html[data-tavern-theme="nocturne"] .stRadioActive{border-color:var(--st-accent);background:rgba(139,147,201,0.16);color:#eef1fb}',
  'html[data-tavern-theme="nocturne"] .stSliderVal{background:rgba(139,147,201,0.20);border-radius:6px;color:#eef1fb}',
  'html[data-tavern-theme="nocturne"] .stSwatch{box-shadow:0 6px 16px rgba(3,5,14,0.55)}',
  'html[data-tavern-theme="nocturne"] .stTrigger{background:linear-gradient(160deg,rgba(30,37,64,0.94),rgba(16,20,37,0.94));border:1px solid var(--st-border);color:#c6cce6;letter-spacing:0.06em;box-shadow:0 14px 34px rgba(3,5,14,0.60)}',
  'html[data-tavern-theme="nocturne"] .stRaw,',
  'html[data-tavern-theme="nocturne"] .stLivePre,',
  'html[data-tavern-theme="nocturne"] .stJsonArea{background:rgba(6,9,20,0.60);border-color:var(--st-border);border-radius:10px;color:#c2c8e0}',
  'html[data-tavern-theme="nocturne"] .stNotice{background:rgba(122,96,32,0.22);border-color:rgba(190,158,98,0.45);color:#e6cf9c}',
  'html[data-tavern-theme="nocturne"] .stEmpty{color:var(--st-text-dim)}',
  'html[data-tavern-theme="nocturne"] .stSpinner{border-color:rgba(139,147,201,0.20);border-top-color:var(--st-accent)}',
  'html[data-tavern-theme="nocturne"] .stPanel ::-webkit-scrollbar{width:10px;height:10px}',
  'html[data-tavern-theme="nocturne"] .stPanel ::-webkit-scrollbar-thumb{background:rgba(139,147,201,0.30);border-radius:999px}',
  'html[data-tavern-theme="nocturne"] .stPanel ::-webkit-scrollbar-track{background:transparent}',
]

/** Every bundled theme, in store display order. */
export const BUILTIN_THEMES: BuiltinTheme[] = [
  {
    id: 'glass',
    display_name: '玻璃拟态',
    author: 'DSH Portable Tavern',
    version: '1.0.0',
    description: '半透明毛玻璃面板叠加柔和光晕渐变，圆角与细边框收束层次，界面轻盈通透。',
    tags: ['深色', '玻璃', '圆角', '现代'],
    css: GLASS_CSS.join('\n'),
  },
  {
    id: 'cyber',
    display_name: '赛博霓虹',
    author: 'DSH Portable Tavern',
    version: '1.0.0',
    description: '深黑底配青与品红双色霓虹描边，扫描线流动、字距加宽，雨夜霓虹街区的味道。',
    tags: ['深色', '霓虹', '赛博', '科幻'],
    css: CYBER_CSS.join('\n'),
  },
  {
    id: 'parchment',
    display_name: '羊皮纸',
    author: 'DSH Portable Tavern',
    version: '1.0.0',
    description: '米黄纸纹与衬线字体，烫金强调色配双线分隔，像翻开一册旧日手札。',
    tags: ['浅色', '纸质', '衬线', '复古'],
    css: PARCHMENT_CSS.join('\n'),
  },
  {
    id: 'sakura',
    display_name: '樱花物语',
    author: 'DSH Portable Tavern',
    version: '1.0.0',
    description: '粉白通透配色配飘落花瓣，柔和阴影与圆润气泡，轻盈得像春日午后。',
    tags: ['浅色', '粉色', '花瓣', '柔和'],
    css: SAKURA_CSS.join('\n'),
  },
  {
    id: 'terminal',
    display_name: '极简终端',
    author: 'DSH Portable Tavern',
    version: '1.0.0',
    description: '纯黑配荧光绿等宽字体，直角边框零阴影，方括号标签与闪烁光标还原 CRT 终端。',
    tags: ['深色', '终端', '等宽', '极简'],
    css: TERMINAL_CSS.join('\n'),
  },
  {
    id: 'nocturne',
    display_name: '夜曲',
    author: 'DSH Portable Tavern',
    version: '1.0.0',
    description: '深蓝紫渐变低饱和配色，衬线正文与舒缓行距，安静耐看的长时间阅读主题。',
    tags: ['深色', '低饱和', '阅读', '优雅'],
    css: NOCTURNE_CSS.join('\n'),
  },
]
